{% set name = "cosmolopy" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e420475419a1cde65a93d38036470d89cf1540ff54a2f0b44ccb85bff2316e16

build:
  number: 3
  skip: True  # [win]
  script: 
    - export CFLAGS="${CFLAGS} -Wno-implicit-function-declaration"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - swig
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python
    - scipy >=1.0

test:
  imports:
    - cosmolopy
    - cosmolopy.EH.power
    - cosmolopy.EH.tf_fit
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/roban/CosmoloPy
  summary: 'a basic numpy/scipy-based cosmology package for python'
  license: MIT
  license_family: MIT
  license_file: LISCENSE

extra:
  recipe-maintainers:
    - beckermr
